services:
  backend:
    restart: always
    build:
      context: ./backend
    ports:
      - "8081:8080"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 1m
      retries: 10
      start_period: 60s
    networks:
      - note-app-net

  frontend:
    restart: always
    build:
      context: ./front
    ports:
      - "81:80"
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - note-app-net

  db:
    image: mysql
    container_name: note-db
    restart: always
    environment:
      MYSQL_DATABASE: "collection"
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    expose: 
      - "3306"
    volumes:
      - mysql-db:/var/lib/mysql
      - .docker/setup.sql:/docker-entrypoint-initdb.d/setup.sql
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-p${MYSQL_ROOT_PASSWORD}",
        ]
      interval: 30s
      timeout: 1m
      retries: 15
      start_period: 60s
    networks:
      - note-app-net

volumes:
  mysql-db:

networks:
  note-app-net:
    driver: bridge
